### ISSUE TITLE
mac line endings not supported

### ISSUE THREAD

**Issue by py1sl** [makeclean/csg2csg#15]
I tried converting an MCNP file originally generated on a Mac.  The line endings in emacs showed as '^M'. 
In notepad++ each text line had an extra blank line, but in emacs or notepad showed a correct mcnp file which mcnp could run. 

 csg2csg however could not run it and threw an error in the __apply_boundary_conditions() function
a bit of sed cmd line trickery sorted the file out but i think csg2csg should probably catch this differently

perhaps one for @Shimwell

**Comment by makeclean** [comment]
You're right, out of curiosity, would MCNP run it without those changes? This brings us all sorts of UTF-8 fun.

**Comment by py1sl** [comment]
yes surprisingly mcnp was fine with it.

i guess i would do an initial test for 'macness' and then kick it back to the user, which simply handles the error in a neater way.

**Comment by Shimwell** [comment]
os.linesep might help

**Comment by py1sl** [comment]
actually perhaps a more simple thing is to just check cell list is not empty, whilst it might be because of macness, it might be any other non compliant text file

**Comment by makeclean** [comment]
Ok, after a little digging there is an easy fix, but the ^M is actually Windows format `/r/n`. I'll push something shortly.
