### ISSUE TITLE
writing material name in OpenMC material file

### ISSUE THREAD

**Issue by Shimwell** [makeclean/csg2csg#19]
Currently it looks like the OpenMC material writer only writes the material id in the materials.xml file

It would be handy if the material name was also included

I have created a [new branch that can do this ](https://github.com/Shimwell/csg2csg/tree/adding_openmc_material_name) 

Unfortunately I based it on the Serpent additions so I shall make a PR once those serpent additions are merged

**Comment by Shimwell** [comment]
I have added some code to write openmc material names out along with the material ID. It appears OpenMC is case sensitive so I was thinking about retaining the case when files are read in and converted. What do you think would this cause to much trouble.

for example reading in a serpent material card when materials have capital letters in them and writing to OpenMC, should we retain the capitalisation?

**Comment by makeclean** [comment]
This was addressed by #18
