### ISSUE TITLE
There is no license

### ISSUE THREAD

**Issue by gonuke** [makeclean/csg2csg#45]
I think this needs a license of some for to allow people to use it legally....

**Comment by Shimwell** [comment]
What do you think @makeclean , shall we put something permissive like the MIT license on this. Might be good to do this before the publication

**Comment by makeclean** [comment]
Yeah I think so, it was funded by H2020 so whatever they require really

On 27 Feb 2020, at 21:52, Jonathan Shimwell <notifications@github.com<mailto:notifications@github.com>> wrote:


What do you think @makeclean<https://github.com/makeclean> , shall we put something permissive like the MIT license on this. Might be good to do this before the publication

**Comment by gvozdila** [comment]
I like that project, i think it has a big future. 
And it looks like license is important part of opensource projects nowadays. 
It looks like according to github docs: https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository#choosing-the-right-license

"You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license."

So now no one can use csg2csg,  except authors.

**Comment by gvozdila** [comment]
So please, could you add any license for csg2csg. 
Otherwise doing 
$ git clone https://github.com/makeclean/csg2csg.git
is a crime

**Comment by Shimwell** [comment]
Haha perhaps this lack of licence is a trick to get more authors 😉. More seriously I think the only thing holding this up is not knowing if horizon 2020 funding requires or recommends a particular licence. Suggestions are welcome

**Comment by gvozdila** [comment]
You could set MIT license for now and ask contributors to join it. 
MIT license allow you do fork|license_change any time you need. 
Or you could set GPL-like license. But changing GPL for program with many authors my be difficult. 
Linux kernel is still GPL2 because it is nearly impossible to all contributors.

**Comment by makeclean** [comment]
i think it needs to be eupl 1.2, i just havent got around to it yet

**Comment by gvozdila** [comment]
Official opensource EU license.
It could work good. License for all EU laws. GPL compatible. 

Only visible  disadvantage is lack of translations to Non-EU languages. But 23 official translations is good enough. 

Looking forward to see LICENSE.md in project
